### ISSUE TITLE
Is the the demo code(universal native & dfp) working well with infinite-scroll page?

### ISSUE THREAD

**Issue by tenthree** [VMFive/vmfive-man-web-demo#2]
### The first ad works well.
![320-one](https://user-images.githubusercontent.com/3132794/32722635-777d7a98-c8a5-11e7-9e89-86c5c53717e7.png)

### But when I render the second ad, I have multiple ads in the same place, and more and more.
![320-full](https://user-images.githubusercontent.com/3132794/32722643-7fbc5422-c8a5-11e7-8e25-f207b9fd184b.png)

**Comment by blackpai** [comment]
Hi @tenthree, could you provide a test page for this issue? We will check and fix it as soon as possible. Thanks.

**Comment by tenthree** [comment]
Hi @blackpai !

You could open the test pen link below. (mobile device or chrome devtool simulation is required)

<a href="https://codepen.io/tenthree/full/YEQaME/" target="_blank">https://codepen.io/tenthree/full/YEQaME/</a>

Thanks.

**Comment by blackpai** [comment]
Hi @tenthree,

We have updated the DFP code to fix duplicating Ads issue. You can check the update [here](https://github.com/VMFive/vmfive-man-web-demo/wiki/VMFive-Ads-Universal-Code#native). 

Thank you!

**Comment by tenthree** [comment]
It works. Thanks help!
